name: FastAPI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest tests/

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t fastapi-app:latest .

      - name: Save Docker Image
        run: docker save -o fastapi-app.tar fastapi-app:latest  # ✅ Save in current directory

      - name: Upload Docker Image as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: fastapi-app.tar  # ✅ Use the correct file path

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .  # ✅ Download to current directory

      - name: Load Docker Image
        run: docker load -i fastapi-app.tar  # ✅ Correct file name

      - name: Run Container
        run: docker run -d -p 8000:8000 --name fastapi-container fastapi-app:latest
